language: php

php:
  - 7.0
  - 7.1
  - 7.2

branches:
  - master

env:
  APP_ENV: testing

install:
  - composer self-update
  - composer install

script:
  - phpunit --bootstrap tests/bootstrap.php tests

